### ISSUE TITLE
Blockchain seeders link error

### ISSUE THREAD

**Issue by martianatwork** [rubykube/workbench#130] opened 2018-08-18 15:31 UTC
On latest master branch

`Link /opt/peatio/config/seed/bitcoin/blockchains.yml -> /home/app/config/seed/bitcoin/blockchains.yml,
/usr/local/lib/ruby/2.5.0/fileutils.rb:323:in `symlink': No such file or directory @ rb_file_s_symlink - (/opt/peatio/config/seed/bitcoin/blockchains.yml, /home/app/config/seed/bitcoin/blockchains.yml) (Errno::ENOENT),
	from /usr/local/lib/ruby/2.5.0/fileutils.rb:323:in `block in ln_s',
	from /usr/local/lib/ruby/2.5.0/fileutils.rb:1479:in `fu_each_src_dest0',
	from /usr/local/lib/ruby/2.5.0/fileutils.rb:321:in `ln_s',
	from bin/link_config:15:in `block in <main>',
	from bin/link_config:12:in `each',
	from bin/link_config:12:in `<main>',`

**Comment by KunwarCG** [comment] 2018-08-18 16:58
+1

**Comment by wooklym** [comment] 2018-08-20 08:17
I solved this problem by `rm config/peatio/seed/bitcoin` after `make bitcoin`.

`app/peatio/link_config` is the cause of this problem, and this file is executed by `make build`.

**Comment by wooklym** [comment] 2018-08-22 11:29
It looks like this was solved in #131

**Comment by shal** [comment] 2018-08-24 20:08
Hello @wooklym, @KunwarCG. 

Fix of this issue was merged to master in #131 pull request.

Thanks for opening issue in workbench!

**Comment by shal** [comment] 2018-08-24 20:09
Closed via #131.

**Closed by shal** 2018-08-24 20:09 UTC
Labels: Type: Bug
