### ISSUE TITLE
How do you configure MySQL to use the correct username and password?

### ISSUE THREAD

**Issue by glaksmono** [rubykube/workbench#249] opened 2018-11-29 07:15 UTC
I've tried to changed the value for the MySQL password in the following files:

	modified:   compose/backend.yaml
	modified:   config/barong.env.erb
	modified:   config/peatio.env.erb

To something like this:

```
DATABASE_HOST=db
DATABASE_USER=root
DATABASE_PASSWORD="123456"
```

But I still keep getting this:

```
Link /opt/peatio/config/seed/currencies.yml -> /home/app/config/seed/currencies.yml
Link /opt/peatio/config/management_api_v1.yml -> /home/app/config/management_api_v1.yml
/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "REDIS_URL". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "ADMIN". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "URL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "LOG_LEVEL". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "OAUTH2_SIGN_IN_PROVIDER". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_ID". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_SECRET". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_DOMAIN". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "JWT_PUBLIC_KEY". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "JWT_AUDIENCE". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_TRADING". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT_API_JWT_PRIVATE_KEY". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT_API_JWT_ALGORITHM". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT_API_RABBITMQ_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT_API_RABBITMQ_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT_API_RABBITMQ_USERNAME". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT_API_RABBITMQ_PASSWORD". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "RANGER_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "RANGER_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)Access denied for user 'root'@'172.19.0.29' (using password: YES)Please provide the root password for your MySQL installation
>123456
Access denied for user 'root'@'172.19.0.29' (using password: YES)
/opt/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
/opt/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:87:in `connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/mysql_database_tasks.rb:8:in `connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/mysql_database_tasks.rb:28:in `rescue in create'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/mysql_database_tasks.rb:14:in `create'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:93:in `create'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:107:in `block in create_current'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:278:in `block in each_current_configuration'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:277:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:277:in `each_current_configuration'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:106:in `create_current'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/bin/rake:23:in `load'
/opt/vendor/bundle/ruby/2.5.0/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "collation"=>"utf8_general_ci", "pool"=>5, "host"=>"db", "port"=>3306, "username"=>"root", "password"=>"123456", "database"=>"peatio_development"}
rake aborted!
Mysql2::Error: Access denied for user 'root'@'172.19.0.29' (using password: YES)
/opt/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
/opt/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:87:in `connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:941:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `up'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:801:in `migrate'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
make: *** [setup-apps] Error 1
```

**Comment by MerlinMagic2018** [comment] 2018-11-29 08:30
I have the exact same issue.

Had to compile an older version without docker.........

**Comment by glaksmono** [comment] 2018-11-29 10:05
@MerlinMagic2018 just changed the DB info to the following:

```
DATABASE_HOST=localhost
DATABASE_USER=root
DATABASE_PASS="123456"
```

Then I'm getting this:

```
Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
```

It's weird because I could login OK if I do `mysql -u root -p 123456`

Thoughts?

**Comment by MerlinMagic2018** [comment] 2018-12-02 20:43
The way I got around this :

https://github.com/rubykube/workbench/wiki/Google-Cloud-Platform-Installation

Using Debian..... It seems that peatio uses ruby 2.5.1 , and barong uses 2.5.3 .

So I followed instructions and it connected without any problems to mysql.....With only this configuration :

 On ubuntu I had the same error and tried multiple workarounds without success.

But then there was another error at this step in the Makefile :

docker-compose run --rm peatio bash -c "./bin/link_config && bundle exec rake db:create db:migrate db:seed"

The error : 
---------------------------
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'quick_withdraw_limit' for Currency


Which I think I saw as another issue lately...... 

I don't know how I came to try this but, I split the command in two :

docker-compose run --rm peatio bash -c "./bin/link_config"

followed by :

docker-compose run --rm peatio bash -c "bundle exec rake db:create db:migrate db:seed"

WEIRD but no error this time.

Then :

cd ~/workbench/app/barong/bin

rbenv install 2.5.3   ( it will take some time..... )
gem install bundler
bundle install          ---------->  which gives this new error : 

Installing mysql2 0.5.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

So then I did :

rbenv global 2.5.3

And reading the error logs, I understood that the mysql libraries are needed even if the mysql2 is in a docker container...... so after some research I did :

sudo apt-get install default-libmysqlclient-dev

And then retried :

bundle install

BOOM it worked and completed. So I retried this :

cd ~/workbench
docker-compose run --rm barong bash -c "./bin/init_config"    ---------> notice here, init_config instead of 

link_config for barong..........

then :

docker-compose run --rm barong bash -c "./bin/setup"

Mysql2::Error::ConnectionError: Access denied for user 'root'@'172.18.0.29' (using password: NO)

**Comment by nithronium** [comment] 2018-12-09 22:41
All of these problems are the actual problems the codes are giving right now. It's not just some people but everyone having these issues. I hope the devs will find the reasons and solve them.

**Comment by MerlinMagic2018** [comment] 2018-12-14 07:56
Ok so I have an hint.

When not using docker containers, installing peatio will eventually give the same error, i.e. can't connect to mysql2......

As seen here : 
https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost

So the solution was :

$ sudo mysql -u root # I had to use "sudo" since is new installation

mysql> USE mysql;
mysql> UPDATE user SET plugin='mysql_native_password' WHERE User='root';
mysql> FLUSH PRIVILEGES;
mysql> exit;

$ service mysql restart

Then it could connect without any problem.

So I believe the same applies to workbench docker containers...... now how to do this in a running container is another thing...... might have to change how the docker container is created....

**Comment by gsilvestri** [comment] 2018-12-14 09:52
Probably you can connect with the PHPMySql admin interface in the workbench instance

**Comment by nithronium** [comment] 2018-12-14 11:14
@MerlinMagic2018 Thanks for the suggestion. However, I feel like there are problems on the main barong configuration files that is trying to use an outdated & false password for MySQL and we get the known error. Instead of solving the problem with mysql, I think we should solve the problem on the repo, so next time if someone tries to install it, they won't have any issue. I will dig into the barong and mysql installation & configuration files and see where is the error.

By the way, did workbench successfully install mysql? I mean, was it only an authentication issue? or you had to re-install mysql too? If it's only authentication issue, can you please share what was the value of "mysql_native_password" field? maybe we can crack the hash and search for that word&password on github repo and edit there.

**Comment by nithronium** [comment] 2018-12-14 12:18
@glaksmono @gsilvestri Okay so after debugging for 10-15 minutes, I have realized that on `workbench/config/barong.env.erb` directory, there are settings for database. However, there is no such parameter as "DATABASE_USER" for mysql, instead, the correct parameter is "DATABASE_USERNAME".

[http://help.collab.net/index.jsp?topic=/teamforge820/reference/var_database_username.html](url)

I already had a fork of workbench on my profile. Can you please try compiling my forked version and let me know if it fixed the problem. I feel like if "DATABASE_USER" is not a valid parameter, it was causing authentication issues since the mysql doesn't know which user is trying to log in.

I am not able to compile & run myself, so, let me know if it fixes the problems.

**Comment by gsilvestri** [comment] 2018-12-14 12:49
I've inserted the line
`DATABASE_PASSWORD='changeme'`
inside the file `workbench/config/barong.env`
Result: the database is accessed again.

However now I have the following exception:
```
D, [2018-12-14T12:39:10.007554 #13] DEBUG -- :   ↳ lib/barong/seed.rb:40
D, [2018-12-14T12:39:10.008897 #13] DEBUG -- :   Level Create (0.3ms)  INSERT INTO `levels` (`id`, `key`, `value`, `description`, `created_at`, `updated_at`) VALUES (3, 'document', 'verified', 'User personal documents have been verified', '2018-12-14 12:39:10', '2018-12-14 12:39:10')
D, [2018-12-14T12:39:10.009350 #13] DEBUG -- :   ↳ lib/barong/seed.rb:40
D, [2018-12-14T12:39:10.019268 #13] DEBUG -- :    (8.5ms)  COMMIT
D, [2018-12-14T12:39:10.019796 #13] DEBUG -- :   ↳ lib/barong/seed.rb:40
I, [2018-12-14T12:39:10.020120 #13]  INFO -- db:seed: Seeding users
rails aborted!
NoMethodError: undefined method `each' for nil:NilClass
/home/app/lib/barong/seed.rb:46:in `seed_users'
/home/app/db/seeds.rb:7:in `<main>'
/home/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
/home/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
```

Something is wrong with the barong db:setup script: however now *I'm able to connect to the Docker MySQL instance from the barong Docker instance.*

**Comment by nithronium** [comment] 2018-12-14 14:46
Okay I first was getting Authentication error but now the error switched to "no password". I will try making the modifications you mentioned on my fork and make the circleci try building again. Also another approach could be comparing the latest working commit and the one after that one. I have seen that 17-18 days ago builds were successful but then later commits caused build errors.

[https://circleci.com/gh/rubykube/workbench](url)

I also think that build problem might have started because of the devs focusing on "microkube" and adjusting the paetio & barong sources for microkube. That might have caused them stop working with workbench.

**Comment by gsilvestri** [comment] 2018-12-14 16:47
I can confirm that the error is using the instruction `DATABASE_PASSWORD='changeme'` instead `DATABASE_PASS='changeme'` in the `workbench/config/barong.eng` file.

**Comment by gsilvestri** [comment] 2018-12-14 17:00
Now I have a problem importing the seed.yml file: it seems that the barong database structure has changed lately: accounts table is changed to users table.

You can check this by comparing the seeds.yml file for Workbench and Microkube applications:
Workbench: https://github.com/rubykube/workbench/blob/master/config/barong/seeds.yml
MicroKube: https://github.com/rubykube/microkube/blob/master/config/barong/seeds.yml

*However I think that this particular issue is closed by using the variable DATABASE_PASS instead DATABASE_PASSWORD in the `workbench/config/barong.env` file. This issue can be closed for me.*

**Comment by MerlinMagic2018** [comment] 2018-12-14 17:49
I edited the following line :

                 password: <%= ENV.fetch('DATABASE_PASS', 'changeme') %>

in workbench/app/barong/config/database.yml

And " make run " completed.

**Closed** 2018-12-19 15:12 UTC

**Comment by TTcoinDeveloper** [comment] 2019-07-13 20:36
Unknown MySQL server host 'db' (-2)
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "pool"=>5, "host"=>"db", "username"=>"root", "password"=>"changeme", "database"=>"barong_development"}
rails aborted!
