### ISSUE TITLE
Configure for server use

### ISSUE THREAD

**Issue by lordvalium** [rubykube/workbench#202] opened 2018-10-05 13:02 UTC
Hi, 

i installed it on my VPS with docker and docker compose. 

I have only an IP Adress. 
Could you please help me how i can call the peatio homepage in the browser?
Guess the hosts entries will not work.

**Comment by knkrth** [comment] 2018-10-06 06:13
Duplicate of issue #190

**Comment by lordvalium** [comment] 2018-10-06 08:38
Yes thx @knkrth i will close

**Closed** 2018-10-06 08:39 UTC
